### ISSUE TITLE
Will this work on windows?

### ISSUE THREAD

**Issue by DarylRob** [berton7/kek-monitors#1]
Sorry for raising an issue for this.. 

I'm starting to learn python programming and want a framework to sort of work backwards on for a monitor and thought yours might be a good start, but will this run on windows?

Cheers,

**Comment by berton7** [comment]
Hi!
Unfortunately no, because they use [asyncio's open_unix_connection](https://docs.python.org/3/library/asyncio-stream.html#asyncio.open_unix_connection) internally to communicate, available only on Unix/Linux. You can run them on [wsl](https://docs.microsoft.com/en-us/windows/wsl/install-win10) tho!

Also, good luck on your programming journey ;)
